### ISSUE TITLE
Editing metadata

### ISSUE THREAD

**Issue by RZiane** [Arborator/arborator-frontend#103] opened 2021-12-09 21:16 UTC
Hi, 
I'm not able to change some metadata (#text) with this pop up:
![image](https://user-images.githubusercontent.com/77019730/145476814-a6c6a2c4-36f6-4e0d-91d9-af3f9f1dad8c.png)

I think it was available before it's not the case anymore.
I would be great if you could bring it back.

**Comment by kimgerdes** [comment] 2021-12-11 10:43
This is a feature, not a bug. You are not supposed to change the text metadata. change it by clicking directly on the text above.

**Comment by kimgerdes** [comment] 2021-12-11 10:46
sorry, i've just noticed that the text line has disappeared in the current prod version.
to be examinated...

**Comment by kirianguiller** [comment] 2022-09-19 13:25
The text metadata is unmodifiable by design.
We should add a special message on this metadata edit window that : "text, sent_id, timestamp, user_id" are unmodifiable. Then we can close the issue.

PS : Thanks Aninda for giving us your opinion on this issue :)

**Closed** 2023-01-04 21:13 UTC
Labels: bug
