### ISSUE TITLE
Disappearance of sentences

### ISSUE THREAD

**Issue by mregnault** [Arborator/arborator-frontend#259] opened 2023-07-26 14:00 UTC
Sentences are successfully loaded from a Github repository. However, after approx. 10 minutes, they all disappear, leaving the repositories empty. The function "Check Pull" does not retrieve the first one, and I have to synchronize anew. I did not get an error message about the file's format, and it passed UD tools' check. Could you please tell me if there is something else I should check?

**Comment by bguil** [comment] 2023-07-26 14:08
We already have identified the problem.
You have to make sure that each sentence contains a metadata called `sent_id`, like in the conll:

```
# sent_id = sentence_001
…
```

We will update the tool to check this and to add `sent_id` when needed. In the meantime, you should add it before uploading.

**Comment by khansadaoudi** [comment] 2023-07-26 14:25
@mregnault  Can you tell us the name of your project

**Comment by mregnault** [comment] 2023-07-28 12:57
@bguil Thank you for your answer, I was able to make it work.

@khansadaoudi The project's name is SILPAC_motion_verbs.

**Comment by khansadaoudi** [comment] 2023-07-28 13:55
Since the problem is solved I can close this isssue

**Closed by khansadaoudi** 2023-07-28 13:55 UTC
