### ISSUE TITLE
Changing AlignBegin and AlignEnd.

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#360] opened 2024-03-14 12:10 UTC
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the figure of AlignBegin and AlignEnd is too long, Arborator rounds up the figure and changes the format. 

### Steps To Reproduce

It concerns a long sample called HAUZ_BC_CONV_04
See an original extract below

![image](https://github.com/Arborator/arborator-frontend/assets/100767065/6d957b44-2fac-45a1-9de7-b3348751f671)

See the uploaded CONLL below: 

1	à	à	ADP	_	_	0	root	_	AlignBegin=1.10094e+06|AlignEnd=1.10111e+06|GE=at|Gloss=at|nWord=1|RX=PREP
2	ìnaː	ìnaː	ADV	_	PronType=Int	1	comp:obj	_	AlignBegin=1.10111e+06|AlignEnd=1.10128e+06|GE=where|Gloss=where|nWord=2|RX=ADV.Q
3	shikè	kè	AUX	_	Person=3	1	comp:cleft	_	AlignBegin=1.10145e+06|AlignEnd=1.10162e+06|GE=3Masc.Ident/Foc.Bkg|Gloss=3Masc.Pred/Loc.Bkg|nWord=4|RX=PART.SYNT|wordform=kèː
4	?//	?//	PUNCT	_	_	1	punct	_	AlignBegin=1.10162e+06|AlignEnd=1.10178e+06|GE=//|Gloss=PUNCT|nWord=5

NB: If I paste the original text here (not a screen shot), I get the same result... 

### Project name

HAU_Zaria

### What browsers are you seeing the problem on?

Firefox

**Comment by bguil** [comment] 2024-03-14 12:14
The problem comes from Grew code. I will fix ASAP.

**Comment by bguil** [comment] 2024-03-18 15:04
The problem is fixed in the code and in the data.

**Closed by bguil** 2024-03-18 15:04 UTC
Labels: bug

**Comment by B-CARON** [comment] 2024-03-18 16:28
Merci.B. Bernard CARON57, avenue d’Italie75013 PARIS06 63 68 15 19 De : Bruno GuillaumeEnvoyé le :lundi 18 mars 2024 16:05À : Arborator/arborator-frontendCc : B-CARON; AuthorObjet :Re: [Arborator/arborator-frontend] Changing AlignBegin and AlignEnd. (Issue #360) The problem is fixed in the code and in the data.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
