### ISSUE TITLE
Problem with the number of the uploaded sentences

### ISSUE THREAD

**Issue by NeldaKote** [Arborator/arborator-frontend#211] opened 2023-03-31 12:25 UTC
Hello, 

I uploaded two different files on my project in Arborator and not all the sentences from the original files are uploaded in the file in the program. In the first file, there are missing 10 sentences and in the second file, there are missing 5 sentences. 
Also, the sentences are not uploaded in the same range that they are on the original file.
Is there any problem?

Thank you, 

Nelda

**Comment by bguil** [comment] 2023-04-01 14:10
Hi @NeldaKote and sorry for the problem you have with the tool!

I've made some test, and I've observed that if several sentences have the same `sent_id`, only one is kept and then the number in the sample is lower than what is observed in the input file. Can you check this in your files?

For the order of the sentences in the file, I cannot reproduce the problem.

To help us investigate, can you send us your data either as an attached file here of by [mail](mailto:Bruno.Guillaume@loria.fr) if you prefer.

**Comment by B-CARON** [comment] 2023-04-02 08:24
The error message associated with file upolad is not as detailed (Error 500) as it used to be. A few days ago, some information was given concerning the error : sent_id ; line number; number of columns (too many or not enough), etc.

**Comment by kirianguiller** [comment] 2023-04-17 12:43
This is a duplication of https://github.com/Arborator/arborator-frontend/issues/212

Moreover, we fixed the problem that @B-CARON mentioned in the precedent message in https://github.com/Arborator/arborator-backend/commit/b860c4ff4fd588f0b2758a03abecf62475ee79f2.

Thanks everyone, I'm closing the issue now.

**Closed by kirianguiller** 2023-04-17 12:43 UTC
