### ISSUE TITLE
Search and replace/delete tool 

### ISSUE THREAD

**Issue by B-CARON** [Arborator/arborator-frontend#224] opened 2023-05-04 13:22 UTC
I tried the following rule on the Darija corpus:

rule r1 { pattern { N [form="<"] } commands { del_node N } }

The number of occurrences found is enormous. (more than 1000). The programme fails to apply the rule on all occurrences. 
I tried on a single file, with around 200 occurrences. It failed again. 

On another rule (16 occurrences) it was no problem. The results were saved on the server.

**Comment by khansadaoudi** [comment] 2023-05-04 13:55
Thanks for reporting, 
Yes when the number of occurences is high, it fail. We are trying to optimize the apply rule feature, we will fix it soon.

**Comment by kirianguiller** [comment] 2023-05-10 13:04
yes. It is indirectly a duplicate of #215

**Closed** 2023-06-07 08:33 UTC
Labels: grew_server
