### ISSUE TITLE
[Bug]: Empty box accepted in upos

### ISSUE THREAD

**Issue by sylvainkahane** [Arborator/arborator-frontend#285] opened 2023-09-16 09:19 UTC
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

In https://arboratorgrew.elizia.net/#/projects/bedja/BEJ_MV_NARR_05_ERITREA, sentence 1 has an empty box in the upos column of the fifth token
As a consequence, it is not possible to click on upos of this token and add one.

### Steps To Reproduce

Click and look.

### What browsers are you seeing the problem on?

Firefox

**Comment by khansadaoudi** [comment] 2023-09-25 13:55
@sylvainkahane I can't reproduce this issue, you can edit the upos of the fifth element directly after clicking of the underscore
![image](https://github.com/Arborator/arborator-frontend/assets/50585493/219e9c82-f8fa-4ef5-9531-2d3c27668ba8)

**Comment by khansadaoudi** [comment] 2023-11-02 09:10
I Think that this issue doesn't exist anymore so I close this issue

**Closed by khansadaoudi** 2023-11-02 09:10 UTC
Labels: bug
