### ISSUE TITLE
"last write / last access" not working

### ISSUE THREAD

**Issue by kirianguiller** [Arborator/arborator-frontend#253] opened 2023-07-10 17:09 UTC
The last write / last access indicator in the project hub page is not working. 

Indeed, for the [chinese beginner treebank](https://arboratorgrew.elizia.net/#/projects/chinese_grammar_wiki_morphSUD), the last read is one week ago, and the last write is three weeks ago. But Yidi worked today on the sample https://arboratorgrew.elizia.net/#/projects/chinese_grammar_wiki_morphSUD/chinese-beginner.B1.mSUD/2163 .

**Comment by khansadaoudi** [comment] 2023-07-21 12:08
@kirianguiller Do you still have this problem, I can't reproduce it, it works fine for me

**Comment by khansadaoudi** [comment] 2023-07-31 08:43
I can close this issue, the last write/ last access indicators work fine

**Comment by kirianguiller** [comment] 2023-09-19 09:50
I'm reopenning the issue. It still doesn't work correctly.

Here is a project where Yidi and me are working daily, but last access and write was 4 weeks ago : 
![image](https://github.com/Arborator/arborator-frontend/assets/35531073/24e64a4b-9d9a-4d23-83f6-549b73f188fa)

**Comment by khansadaoudi** [comment] 2023-10-17 08:46
fixed in this [commit](https://github.com/Arborator/arborator-backend/commit/cca14829fa714064b8f276b7b59eca2a4829d4c3)

**Closed by khansadaoudi** 2023-10-17 08:46 UTC
