### ISSUE TITLE
[Bug]: Unable to manually type accented characters in "lemma" field

### ISSUE THREAD

**Issue by Lguyogiro** [Arborator/arborator-frontend#270] opened 2023-08-08 01:14 UTC
### Is there already an issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click on a token/lemma and get to the pop up menu for updating the form and lemma, I am unable to type accented characters into the lemma field. I have a Spanish language layout keyboard, and type diacritics by using two-keystroke combinations (diacritic character + character to be accented)

E.g. when editing a Spanish sentence, the lemma should be "él", but the first keystroke, "´", is immediately erased and the resulting lemma is "el".

### Steps To Reproduce

1. Click on a lemma in a tree
2. Update the "Lemma" field by typing something with a diacritic such as "´" or "^".
3. Notice that the diacritic is not included in the lemma field.

### Project name

bangor_miami_codeswitching

### What browsers are you seeing the problem on?

Firefox

**Comment by bguil** [comment] 2023-09-01 07:56
I cannot reproduce the problem. I've made many tests with diacritics and the field always contains the expected value.
Do you observe the same problem in other applications?, in other places in ArboratorGrew (for instance when you edit the project description).
Maybe another solution to enter diacritics: a long press on the `e` key open a small window (on my mac computer at least) where you can chose the letter with some diacritics:
<img width="211" alt="Screenshot 2023-09-01 at 09 54 26" src="https://github.com/Arborator/arborator-frontend/assets/687155/cfc835c4-af77-4fb6-b0df-baefc026138c">

**Comment by khansadaoudi** [comment] 2023-09-27 13:45
I've made other tests on Linux and I couldn't reproduce it

**Comment by khansadaoudi** [comment] 2023-10-11 10:47
Since there is no answer I will close this issue

**Closed by khansadaoudi** 2023-10-11 10:47 UTC
Labels: bug
